CONFIG_ZMK_USB_LOGGING=n
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_MOUSE=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_PHY_2M=n

# MacやWindowsでの接続安定性を飛躍的に向上させる
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# デバイスのAppearanceをマウスに設定
CONFIG_BT_DEVICE_APPEARANCE=962

CONFIG_BT_DEVICE_APPEARANCE=962
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

CONFIG_PMW3610=y
CONFIG_PMW3610_ORIENTATION_90=y
CONFIG_PMW3610_INVERT_X=n
CONFIG_PMW3610_INVERT_Y=n
CONFIG_PMW3610_CPI=2600
CONFIG_PMW3610_SNIPE_CPI=2600

CONFIG_ZMK_IDLE_TIMEOUT=20000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6

